const FETCH_ALL_PLANS = "FETCH_ALL_PLANS";
const CREATE_PLAN = "CREATE_PLAN";
const UPDATE_PLAN = "UPDATE_PLAN";
const DELETE_PLAN = "DELETE_PLAN";

export {
    FETCH_ALL_PLANS,
    CREATE_PLAN,
    UPDATE_PLAN,
    DELETE_PLAN,
}

